# -*- coding: utf-8 -*-
"""phonebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BlVPPmYen4F2YHM87z7K7aF7M-U4DD5b
"""

#New database connection
import pymongo
from pymongo import MongoClient
client = pymongo.MongoClient("mongodb+srv://alfred:1234@cluster0.ydwyn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.Alfred # New database named 'Alfred'
table = db.Deva # New collection name 'Deva'

#Phonebook Project 
choice=5
while choice!=0:
  print("Enter your choice 1.Create Contact 2.Search Contact 3.Delete Contact 4.Display Contact 5.Exit the application ")
  print("Enter the number with your choice ")
  choice=int(input())
  if choice>5:
    print("INVALID CHOICE enter correct number ")
  elif choice==1:
    name=input("Enter your Name ")
    phno=input("Enter your phone number ")
    cnf=input("Is this your whatsapp number? ")
    y = {
    "name": name,
    "phno": phno,
    "confirmation": cnf
    }
    table.insert_one(y)
    continue

  elif choice==2:
    search=input("Enter the Name you wish to search ")
    query1={"name": search}
    records=table.find(query1,{"_id":0,"name":1,"phno":1})
    for x in records:
      print(x)

  elif choice==3:
    for x in table.find({},{"_id": 0,"name": 1,"rollno": 1}): 
      print(x)
    name=input("Enter the Name you wish to delete ")
    query2={"name":name}
    table.delete_one(query2)
    print("deleted successfully")
    for x in table.find({},{"_id": 0,"name": 1,"rollno": 1}):
      print(x)
    continue

  elif choice==4:
    for x in table.find(): 
      print(x)
    print(table.count_documents({}))  # prints no. of records

  else:
    print("Thank you for using the application  ")
    break

import pymongo
from pymongo import MongoClient
client = pymongo.MongoClient("mongodb+srv://alfred:1234@cluster0.ydwyn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.Alfred # New database named 'Alfred'
table = db.Deva # New collection name 'Deva'


#Banking System 
records.drop() # to delete a table or collection

myquery={"saasd":"2323"}
newvalues={"$set":{"name":"lit"}}#changes all the values of name lit to the myquery. $- symbol all the elemt
#$set()-aggregation appends new fields to exsisting oprands
records.update_one() #first element gets updated
#Field update operators

up={
"$currentDate":{
    "lastmodified":False
}
}
query={"name":"sonia"}
newvalues={"$set": {"name":"Alfred"} }
table.update_one(query,newvalues)
table.update_one(query,up)

data={
    "_id":22,
    "name":"fig",
    "quantity":10,
    "metrics":{
        "orders":4,
        "ratings":3.5
    }
}
table.insert_one(data)

query2={"_id":22}
newvalues1={"$inc": {"quantity":-2,"metrics.rating":1} }
table.update_one(query2,newvalues1)

# Collection methods db.collection.deleteOne....deleteMany....count...distinct
# One to one relationship
#patron document
polo = {
    "_id":"nirmal",
    "name":"joker"
}
# address document 
polo1 = {
    "patron_id":"nirmal", # by referncing we r embedding
    "street":"ashok nagar",
    "pincode":"656455",
    "state":"tamilnadu"
}
table.insert_one(polo)
table.insert_one(polo1)

#embedded document decrease complexityyy
polo2={
    "_id":"nirmal4",
    "name":"joker2",
    "address":{
    "street":"ashok nagar",
    "pincode":"656455",
    "state":"tamilnadu",
          "Communication address":{ #object within a object
                      "lane":"2nd lane",
                        "doorno":"23"
                                   },
           "permanet address":{
        "same as above":"above"
                    }
    }

}
table.insert_one(polo2)

#Banking application part 2 https://www.mongodb.com/developer/quickstart/cheat-sheet/   https://cheatography.com/isaeus/cheat-sheets/mongodb/

#One to many relationship
list=[new,new1,new2]
records.insert_many(list)

import pymongo
from pymongo import MongoClient
client = pymongo.MongoClient("mongodb+srv://alfred:1234@cluster0.ydwyn.mongodb.net/myFirstDatabase?retryWrites=true&w=majority")
db = client.Alfred # New database named 'Alfred'
table = db.Deva # New collection name 'Deva'

polo2={
      "_id":"nirmal4",
        "name":"joker2",   #[]----> array {}----->object
        "address": [
        {
    'street' : "ashok nagar",
    'pincode':"656455",
    'state':"tamilnadu"
        },
        {
    'street' : "ashok nagar",
    'pincode':"656455",
    'state':"tamilnadu"   
        }
          ]
    }
table.insert_one(polo2)



publisher={
   id=555
}
book1={
    pid=555
}
book2={
    pid=555
}

